apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-s8ho
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-s8ho
    app.kubernetes.io/part-of: hacbs-probe-payload
  name: devfile-sample-go-basic-s8ho
  namespace: mreid-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-go-basic-s8ho
status:
  loadBalancer: {}
